<script setup lang="ts">
/**
 * Coverage tab: the latest CI-generated coverage figures per test type.
 * Loads eagerly on mount (parent keeps every panel mounted via v-show).
 */
import { computed, onMounted, ref } from 'vue'
import { AppBadge, AppBanner } from '@/components/app'
import { getCoverage, type CoverageInfo, type CoverageSide } from '@/api/admin'

const cardClass = 'card p-6'

const coverage = ref<CoverageInfo | null>(null)
const coverageLoading = ref(true)
const coverageError = ref<string | null>(null)

/** Render a percentage as "95.2%" or a dash when unmeasured. */
function formatPct(pct: number | null): string {
  return pct === null ? '—' : `${pct}%`
}

interface CoverageTypeView {
  key: string
  label: string
  runner: string
  description: string
  /** Line-coverage detail for the unit suites; null for e2e / compose-smoke. */
  side: CoverageSide | null
  /** Whether the side meets its gate; null when there is no line coverage. */
  passes: boolean | null
}

/**
 * Every CI test type, in pipeline order, each joined to its line-coverage side
 * when it has one (backend/frontend) — so the tab reflects all four kinds of
 * test CI runs, not just the two that produce coverage. Falls back to the two
 * known sides if an older baked summary has no `test_types` list.
 */
const coverageTypes = computed<CoverageTypeView[]>(() => {
  const c = coverage.value
  if (!c) return []
  const sideFor = (key: string): CoverageSide | null =>
    key === 'backend' ? c.backend : key === 'frontend' ? c.frontend : null
  const passesFor = (side: CoverageSide | null): boolean | null =>
    side && side.pct !== null && side.threshold !== null ? side.pct >= side.threshold : null
  const types =
    c.test_types.length > 0
      ? c.test_types
      : [
          { key: 'backend', label: 'Backend', runner: 'pytest', has_coverage: true, description: '' },
          {
            key: 'frontend',
            label: 'Frontend',
            runner: 'Vitest',
            has_coverage: true,
            description: '',
          },
        ]
  return types.map((t) => {
    const side = t.has_coverage ? sideFor(t.key) : null
    return {
      key: t.key,
      label: t.label,
      runner: t.runner,
      description: t.description,
      side,
      passes: passesFor(side),
    }
  })
})

async function loadCoverage(): Promise<void> {
  coverageLoading.value = true
  coverageError.value = null
  try {
    coverage.value = await getCoverage()
  } catch {
    coverageError.value = 'Could not load coverage data. Try refreshing the page.'
  } finally {
    coverageLoading.value = false
  }
}

onMounted(() => {
  void loadCoverage()
})
</script>

<template>
  <p v-if="coverageLoading" data-testid="coverage-loading" class="text-gray-600 dark:text-gray-300">
    Loading coverage data…
  </p>
  <AppBanner v-else-if="coverageError" variant="error" data-testid="coverage-error">
    {{ coverageError }}
  </AppBanner>
  <div
    v-else-if="coverage && !coverage.available"
    data-testid="coverage-unavailable"
    class="bg-white dark:bg-gray-800 border-l-4 border-yellow-500 rounded-lg px-4 py-3 shadow-xs text-gray-700 dark:text-gray-200"
  >
    Coverage data unavailable (generated by CI).
  </div>
  <div v-else-if="coverage" class="space-y-6">
    <!-- One card per CI test type (.github/workflows/ci.yml), in pipeline
         order. The two unit suites show headline %, gate pass/fail, file
         counts and the lowest-covered files; e2e / compose-smoke have no
         line coverage and show what they exercise + that they gate in CI. -->
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
      <div
        v-for="t in coverageTypes"
        :key="t.key"
        :class="cardClass"
        :data-testid="`coverage-card-${t.key}`"
      >
        <div class="flex items-center justify-between gap-3 mb-1">
          <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-100">{{ t.label }}</h2>
          <AppBadge v-if="t.passes !== null" :colour="t.passes ? 'green' : 'red'">
            {{ t.passes ? 'Pass' : 'Below gate' }}
          </AppBadge>
          <AppBadge v-else colour="grey">CI gate</AppBadge>
        </div>
        <p class="text-xs text-gray-500 dark:text-gray-400 mb-3">{{ t.runner }}</p>

        <template v-if="t.side">
          <p
            class="text-3xl font-bold text-gray-800 dark:text-gray-100"
            :data-testid="`coverage-${t.key}`"
          >
            {{ formatPct(t.side.pct) }}
          </p>
          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
            <span v-if="t.side.threshold != null">Gate {{ t.side.threshold }}%</span>
            <span v-if="t.side.files_total != null"> · {{ t.side.files_total }} files</span>
            <span v-if="t.side.files_below_gate != null">
              · {{ t.side.files_below_gate }} below gate
            </span>
          </p>

          <div v-if="t.side.worst_files.length" class="mt-4">
            <h3 class="mb-2 text-sm font-semibold text-gray-700 dark:text-gray-200">
              Lowest-covered files
            </h3>
            <ul class="divide-y divide-gray-100 dark:divide-gray-700/60">
              <li
                v-for="f in t.side.worst_files"
                :key="f.path"
                class="flex items-center justify-between gap-3 py-1.5 text-sm"
              >
                <span class="min-w-0 truncate font-mono text-xs text-gray-600 dark:text-gray-300">
                  {{ f.path }}
                </span>
                <span
                  class="shrink-0 font-semibold"
                  :class="
                    t.side.threshold != null && f.pct < t.side.threshold
                      ? 'text-red-600 dark:text-red-400'
                      : 'text-gray-800 dark:text-gray-100'
                  "
                >
                  {{ formatPct(f.pct) }}
                </span>
              </li>
            </ul>
          </div>
        </template>

        <!-- e2e / compose-smoke: no line coverage, just what they cover. -->
        <p
          v-else
          class="text-sm text-gray-600 dark:text-gray-300"
          :data-testid="`coverage-note-${t.key}`"
        >
          {{ t.description }}
        </p>
      </div>
    </div>

    <!-- When + which build produced these numbers. -->
    <div :class="cardClass">
      <dl class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
        <div>
          <dt class="text-gray-500 dark:text-gray-400">Generated</dt>
          <dd class="text-gray-800 dark:text-gray-100" data-testid="coverage-generated">
            {{ coverage.generated_at ?? '—' }}
          </dd>
        </div>
        <div>
          <dt class="text-gray-500 dark:text-gray-400">Git SHA</dt>
          <dd
            class="text-gray-800 dark:text-gray-100 font-mono break-all"
            data-testid="coverage-git-sha"
          >
            {{ coverage.git_sha ?? '—' }}
          </dd>
        </div>
      </dl>
    </div>
  </div>
</template>
