/**
 * Typed API for the admin endpoints (all under /api/admin/*).
 *
 * Every endpoint requires an admin session: non-admins receive 403 and
 * anonymous callers 401. The router's admin guard keeps non-admins out of the
 * UI, so these functions assume an admin caller and surface any error via the
 * shared `ApiError` from the fetch wrapper.
 */

import { apiFetch } from './client'

/** Aggregate counts for the system dashboard. */
export interface DbStats {
  documents_total: number
  documents_deleted: number
  documents_by_status: Record<string, number>
  users_total: number
  users_active: number
  jobs_total: number
  jobs_active: number
  extraction_cost_usd_total: number
}

/** One deployed service in the stack (name + its role). */
export interface DeploymentService {
  name: string
  role: string
}

/** GET /api/admin/system — version, deployment topology, config and stats. */
export interface SystemInfo {
  version: string
  git_sha: string | null
  deployment: DeploymentService[]
  config: Record<string, unknown>
  stats: DbStats
}

/** One architecture document, with its raw markdown body. */
export interface ArchitectureDoc {
  name: string
  title: string
  markdown: string
}

/** GET /api/admin/architecture — the rendered architecture docs. */
export interface ArchitectureInfo {
  docs: ArchitectureDoc[]
}

/** One side's coverage: measured pct and the configured gate, either nullable. */
export interface CoverageSide {
  pct: number | null
  threshold: number | null
}

/** GET /api/admin/coverage — backend/frontend coverage as last generated by CI. */
export interface CoverageInfo {
  available: boolean
  backend: CoverageSide | null
  frontend: CoverageSide | null
  generated_at: string | null
  git_sha: string | null
}

/** A user row in the admin users table. */
export interface AdminUser {
  id: number
  username: string
  display_name: string
  is_admin: boolean
  is_active: boolean
  created_at: string
}

/** Body for POST /api/admin/users. */
export interface CreateUserBody {
  username: string
  password: string
  display_name?: string
  is_admin?: boolean
}

/** Body for PATCH /api/admin/users/{id} — both fields optional. */
export interface UpdateUserBody {
  is_admin?: boolean
  is_active?: boolean
}

/** GET /api/admin/system — system overview for the admin dashboard. */
export function getSystemInfo(signal?: AbortSignal): Promise<SystemInfo> {
  return apiFetch<SystemInfo>('/api/admin/system', { signal })
}

/** GET /api/admin/architecture — architecture docs (markdown). */
export function getArchitecture(signal?: AbortSignal): Promise<ArchitectureInfo> {
  return apiFetch<ArchitectureInfo>('/api/admin/architecture', { signal })
}

/** GET /api/admin/coverage — latest CI-generated coverage figures. */
export function getCoverage(signal?: AbortSignal): Promise<CoverageInfo> {
  return apiFetch<CoverageInfo>('/api/admin/coverage', { signal })
}

/** GET /api/admin/users — every user (active and deactivated). */
export function listUsers(signal?: AbortSignal): Promise<AdminUser[]> {
  return apiFetch<AdminUser[]>('/api/admin/users', { signal })
}

/** POST /api/admin/users — create a user; returns the created record (201). */
export function createUser(body: CreateUserBody): Promise<AdminUser> {
  return apiFetch<AdminUser>('/api/admin/users', { method: 'POST', body })
}

/** PATCH /api/admin/users/{id} — toggle a user's admin/active flags. */
export function updateUser(id: number, body: UpdateUserBody): Promise<AdminUser> {
  return apiFetch<AdminUser>(`/api/admin/users/${id}`, { method: 'PATCH', body })
}
