/**
 * Typed API for the admin endpoints (all under /api/admin/*).
 *
 * Every endpoint requires an admin session: non-admins receive 403 and
 * anonymous callers 401. The router's admin guard keeps non-admins out of the
 * UI, so these functions assume an admin caller and surface any error via the
 * shared `ApiError` from the fetch wrapper.
 */

import { apiFetch } from './client'

// The recipients management panel reuses the public list endpoint rather than
// duplicating it; re-exported here so the panel imports everything from one
// module (and so a single mock of `@/api/admin` covers the whole panel).
export { listRecipients } from './taxonomy'
export type { RecipientOption } from './taxonomy'

/** Aggregate counts for the system dashboard. */
export interface DbStats {
  documents_total: number
  documents_deleted: number
  documents_by_status: Record<string, number>
  users_total: number
  users_active: number
  jobs_total: number
  jobs_active: number
  extraction_cost_usd_total: number
}

/** One deployed service in the stack (name + its role). */
export interface DeploymentService {
  name: string
  role: string
}

/** GET /api/admin/system — version, deployment topology, config and stats. */
export interface SystemInfo {
  version: string
  git_sha: string | null
  deployment: DeploymentService[]
  config: Record<string, unknown>
  stats: DbStats
}

/** One architecture document, with its raw markdown body. */
export interface ArchitectureDoc {
  name: string
  title: string
  markdown: string
}

/** GET /api/admin/architecture — the rendered architecture docs. */
export interface ArchitectureInfo {
  docs: ArchitectureDoc[]
}

/** One file's line-coverage percentage (worst-offenders list). */
export interface CoverageFile {
  path: string
  pct: number
}

/**
 * One side's coverage: measured pct and the configured gate (either nullable),
 * plus per-file detail. The per-file fields are null/empty for older
 * totals-only summaries.
 */
export interface CoverageSide {
  pct: number | null
  threshold: number | null
  files_total: number | null
  files_below_gate: number | null
  worst_files: CoverageFile[]
}

/** GET /api/admin/coverage — backend/frontend coverage as last generated by CI. */
export interface CoverageInfo {
  available: boolean
  backend: CoverageSide | null
  frontend: CoverageSide | null
  generated_at: string | null
  git_sha: string | null
}

/** A user row in the admin users table. */
export interface AdminUser {
  id: number
  username: string
  display_name: string
  is_admin: boolean
  is_active: boolean
  created_at: string
}

/** Body for POST /api/admin/users. */
export interface CreateUserBody {
  username: string
  password: string
  display_name?: string
  is_admin?: boolean
}

/** Body for PATCH /api/admin/users/{id} — both fields optional. */
export interface UpdateUserBody {
  is_admin?: boolean
  is_active?: boolean
}

/** GET /api/admin/system — system overview for the admin dashboard. */
export function getSystemInfo(signal?: AbortSignal): Promise<SystemInfo> {
  return apiFetch<SystemInfo>('/api/admin/system', { signal })
}

/** GET /api/admin/architecture — architecture docs (markdown). */
export function getArchitecture(signal?: AbortSignal): Promise<ArchitectureInfo> {
  return apiFetch<ArchitectureInfo>('/api/admin/architecture', { signal })
}

/** GET /api/admin/coverage — latest CI-generated coverage figures. */
export function getCoverage(signal?: AbortSignal): Promise<CoverageInfo> {
  return apiFetch<CoverageInfo>('/api/admin/coverage', { signal })
}

/** GET /api/admin/users — every user (active and deactivated). */
export function listUsers(signal?: AbortSignal): Promise<AdminUser[]> {
  return apiFetch<AdminUser[]>('/api/admin/users', { signal })
}

/** POST /api/admin/users — create a user; returns the created record (201). */
export function createUser(body: CreateUserBody): Promise<AdminUser> {
  return apiFetch<AdminUser>('/api/admin/users', { method: 'POST', body })
}

/** PATCH /api/admin/users/{id} — toggle a user's admin/active flags. */
export function updateUser(id: number, body: UpdateUserBody): Promise<AdminUser> {
  return apiFetch<AdminUser>(`/api/admin/users/${id}`, { method: 'PATCH', body })
}

/**
 * DELETE /api/admin/users/{id} — permanently delete a user.
 *
 * Guarded server-side: deleting your own account is `400` and deleting the last
 * active admin is `409` (both surfaced via `ApiError`). The user's linked
 * recipient survives (its `user_id` is nulled), so addressed documents are kept.
 */
export function deleteUser(id: number): Promise<void> {
  return apiFetch<void>(`/api/admin/users/${id}`, { method: 'DELETE' })
}

// --- Recipients -------------------------------------------------------------

/** The renamed recipient (or the merge target, when a merge was performed). */
export interface RecipientRef {
  id: number
  name: string
}

/**
 * Body of the 409 returned by `renameRecipient` when the new name collides
 * (case-insensitive) with another recipient and `merge` was not set. Re-call
 * with `merge: true` to fold this recipient into the named target.
 * Read off `ApiError.body` (see `client.ts`).
 */
export interface RecipientRenameConflict {
  detail: string
  target_id: number
  target_name: string
  target_document_count: number
}

/**
 * Body of the 409 returned by `deleteRecipient` when the recipient still owns
 * documents and `reassignTo` was omitted. Read off `ApiError.body`.
 */
export interface RecipientDeleteConflict {
  detail: string
  document_count: number
}

/**
 * PATCH /api/admin/recipients/{id} — rename a recipient, or (when `merge`)
 * fold it into the existing recipient with the target name. Without `merge`, a
 * name collision rejects with a 409 carrying a `RecipientRenameConflict` body.
 */
export function renameRecipient(id: number, name: string, merge = false): Promise<RecipientRef> {
  return apiFetch<RecipientRef>(`/api/admin/recipients/${id}`, {
    method: 'PATCH',
    body: merge ? { name, merge: true } : { name },
  })
}

/**
 * DELETE /api/admin/recipients/{id}.
 *
 * The `reassign_to` query param encodes three intents:
 *   - `reassignTo` omitted (`undefined`) → the param is left off entirely, which
 *     triggers the 409 guard (`RecipientDeleteConflict`) when the recipient
 *     still has documents.
 *   - `reassignTo === null` → sends `reassign_to=` (empty), clearing the
 *     recipient on its documents before deleting.
 *   - `reassignTo` a number → sends `reassign_to=<id>`, moving the documents to
 *     that recipient before deleting.
 */
export function deleteRecipient(id: number, reassignTo?: number | null): Promise<void> {
  const query: Record<string, string | number | undefined> = {}
  if (reassignTo !== undefined) {
    query.reassign_to = reassignTo === null ? '' : reassignTo
  }
  return apiFetch<void>(`/api/admin/recipients/${id}`, { method: 'DELETE', query })
}
